# Lua type check against the Factorio API (catches typos like player.get_main_inventry or event.player_indx).
# Lua Language Server in --check mode + Factorio API types generated by FMTK for the exact game version.
# Used through docker-compose.yml (service "typecheck") and run-tests.ps1.
FROM node:22-bookworm-slim

ARG FACTORIO_VERSION=2.1.20
ARG LUALS_VERSION=3.19.1
ARG FMTK_VERSION=2.1.9

RUN apt-get update \
 && apt-get install -y --no-install-recommends ca-certificates curl \
 && rm -rf /var/lib/apt/lists/*

RUN mkdir -p /opt/luals \
 && curl -fsSL "https://github.com/LuaLS/lua-language-server/releases/download/${LUALS_VERSION}/lua-language-server-${LUALS_VERSION}-linux-x64.tar.gz" \
    | tar -xz -C /opt/luals \
 && /opt/luals/bin/lua-language-server --version

# Factorio API types (LuaPlayer, defines, prototypes, typed events, ...) from lua-api.factorio.com/<version>/
WORKDIR /opt/fmtk
RUN npm init -y >/dev/null \
 && npm install --no-audit --no-fund "factoriomod-debug@${FMTK_VERSION}" \
 && (npx --no-install fmtk luals-addon --online "${FACTORIO_VERSION}" /opt/factorio-types \
     || (echo "Could not fetch API docs for Factorio ${FACTORIO_VERSION} from lua-api.factorio.com" >&2; exit 1)) \
 && test -f /opt/factorio-types/factorio/plugin.lua

COPY typecheck.sh /usr/local/bin/typecheck
COPY typecheck-report.js /usr/local/lib/typecheck-report.js
RUN sed -i 's/\r$//' /usr/local/bin/typecheck && chmod +x /usr/local/bin/typecheck

WORKDIR /data
ENTRYPOINT ["typecheck"]
CMD ["src"]
